name: Windows Node CI

on:
  push:
    paths-ignore:
      - 'homepage/**'

jobs:
  win_build_and_test:
    if: ${{ github.event.repository.fork == true }}
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install (skip postinstall in fork)
        run: |
          npm ci --ignore-scripts
      - name: integration test (upstream only)
        if: ${{ github.event.repository.fork != true }}
        run: |
          npm run integration:win -- "sharedProject"
        env:
          VITEST: true
          APPVEYOR: true
      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: logs
      - name: build
        run: |
          npm run dist:appveyor -- --win
        env:
          APPVEYOR: true
          CI: false
          RELEASE_BUILD: ${{startsWith(github.ref, 'refs/tags/')}}
          BUILD_NUMBER: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}
          VITE_BUILD_NUMBER: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}
      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots
      - name: Upload build artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/KnowclipExtra_*
      # release steps removed to avoid notifications in upstream or external users
